FROM {{ namespace }}/base-tools:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get install -y --no-install-recommends \
        mariadb-server-10.1 \
        percona-xtrabackup \
        socat \
        expect \
    && apt-get clean \
    && rm -rf /var/lib/mysql/*

COPY mariadb_sudoers /etc/sudoers.d/mariadb_sudoers
COPY bootstrap.sh /usr/local/bin/bootstrap.sh
COPY security_reset.expect /usr/local/bin/mysql_security_reset
RUN chmod 755 /usr/local/bin/bootstrap.sh \
    && chmod 755 /usr/local/bin/mysql_security_reset \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/mariadb_sudoers \
    && usermod -a -G microservices mysql
