FROM {{ namespace }}/base:{{ tag }}
MAINTAINER {{ maintainer }}

ENV DEBIAN_FRONTEND noninteractive

COPY jq /usr/bin/jq
COPY clustercheckcron /usr/bin/clustercheckcron
COPY percona_sources.list /etc/apt/sources.list.d/

RUN apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
RUN apt-get update
RUN apt-get install -y --no-install-recommends percona-xtradb-cluster-57

ADD node.cnf /etc/my.cnf
VOLUME /var/lib/mysql

RUN chmod a+x /usr/bin/jq
RUN chmod a+x /usr/bin/clustercheckcron
